stages:
  - build
  - push
  - deploy
  - hub_push
  - nm_stage_deploy

variables:
  # IMAGE_GROUP: xxx
  # NAME_SPACE: xxx
  # GOPATH: ${CI_PROJECT_DIR}/.go
  # GOMODCACHE: ${CI_PROJECT_DIR}/.go/pkg/mod
  # GOCACHE: ${CI_PROJECT_DIR}/.go/.cache/go-build
  # GOLANGCI_LINT_CACHE: ${CI_PROJECT_DIR}/.go/.cache/golangci-lint

build:
  only:
    - main
  stage: build
  image: node:21 
  script:
    - yarn add typescript --dev
    - yarn
    - yarn build
    - rm -rf /data/artifacts/merchant_portal_dist
    - cp -r dist /data/artifacts/merchant_portal_dist

push:
  only:
    - main
  image: docker
  stage: push
  script:
    - rm -rf dist
    - cp -r /data/artifacts/merchant_portal_dist dist
    - docker build -t easzlab.io.local:5000/unibee/unibee-merchant-portal:daily .
    - docker push easzlab.io.local:5000/unibee/unibee-merchant-portal:daily

deploy:
  only:
    - main
  image: registry.cn-shenzhen.aliyuncs.com/heiku/kubectl:latest
  stage: deploy
  script:
    - kubectl --kubeconfig ${KUBE_FILE} rollout restart deployment/yd-oss-unib-merchant-protal-prod


hub_push:
  only:
    - main
  image: docker
  stage: hub_push
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker tag easzlab.io.local:5000/unibee/unibee-merchant-portal:daily unibee/admin-portal:stage
    - docker push unibee/admin-portal:stage

# nm_stage_deploy:
#   only:
#     - main
#   image: registry.cn-shenzhen.aliyuncs.com/heiku/kubectl:latest
#   stage: deploy
#   script:
#     - kubectl --kubeconfig /data/kubeconfigs/nodemaven_dev_config rollout restart deployment/unibee-admin-protal